services:
  proxy:
    image: nginx:stable-alpine3.20
    volumes:
      -./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      -80:80
    restart: unless-stopped
    depends_on:
      - rest-server
      - tcp-server
  rest-server:
    build:
      context: "./RestServer"
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    depends_on:
      - db
  tcp-server:
    build:
      context: "./TcpServer"
      dockerfile: Dockerfile
    expose:
      - 4000
    restart: unless-stopped
    depends_on:
       - db
  db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: db_pass
    user: root
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "./postgres/data/:/var/lib/postgresql/data"
    restart: always

secrets:
  db_pass:
    file:Secrets/db_pass.txt