services:
  proxy:
    image: nginx:stable-alpine3.20
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - rest-server
      - tcp-server
  rest-server:
    build:
      context: "./RestServer"
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    depends_on:
      - db
  tcp-server:
    build:
      context: "./TcpServer"
      dockerfile: Dockerfile
    expose:
      - 4000
    restart: unless-stopped
    depends_on:
       - db
  db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    user: root
    expose:
      - 5001
    ports:
      - 5001:5001
    volumes:
      - "./postgres/data/:/var/lib/postgresql/data"
    restart: always